/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary": "#4c616c",
        "tertiary-fixed-dim": "#eebd8e",
        "on-secondary-fixed-variant": "#354a53",
        "outline": "#747781",
        "secondary-fixed-dim": "#b4cad6",
        "surface-container-high": "#e6e8e9",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#abc7ff",
        "tertiary-fixed": "#ffdcbd",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#24467c",
        "on-secondary-container": "#526772",
        "surface-tint": "#3e5e95",
        "on-primary-fixed": "#001b3f",
        "on-surface-variant": "#43474f",
        "primary-container": "#002d62",
        "outline-variant": "#c4c6d1",
        "primary": "#00193c",
        "on-primary-container": "#7796d1",
        "tertiary": "#2a1500",
        "secondary-container": "#cfe6f2",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#61401b",
        "tertiary-container": "#452805",
        "primary-fixed": "#d7e2ff",
        "on-primary": "#ffffff",
        "inverse-surface": "#2e3132",
        "surface": "#f8fafb",
        "on-secondary-fixed": "#071e27",
        "surface-bright": "#f8fafb",
        "surface-variant": "#e1e3e4",
        "inverse-on-surface": "#eff1f2",
        "secondary-fixed": "#cfe6f2",
        "surface-container-highest": "#e1e3e4",
        "on-tertiary-container": "#ba8e62",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container": "#eceeef",
        "on-tertiary-fixed": "#2c1600",
        "surface-container-lowest": "#ffffff",
        "background": "#f8fafb",
        "on-background": "#191c1d",
        "surface-container-low": "#f2f4f5",
        "inverse-primary": "#abc7ff",
        "on-tertiary": "#ffffff",
        "surface-dim": "#d8dadb",
        "on-surface": "#191c1d",
      },
      fontFamily: {
        "serif": ["Noto Serif", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"],
        "sans": ["Manrope", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "2xl": "0.75rem",
        "3xl": "1rem",
        "full": "9999px",
      },
    },
  },
  plugins: [],
}

